In [1]:
from joblib import dump, load
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Trees Approach
from sklearn.tree import DecisionTreeClassifier
# Ensemble Approach
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier


In [2]:
#import the data
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
#importing data
train_path = '/content/drive/MyDrive/data/large_data.csv'
test_path = '/content/drive/MyDrive/data/student_data.csv'

In [4]:
train_df = pd.read_csv(train_path)
train_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120960 entries, 0 to 120959
Data columns (total 7 columns):
 #   Column                                                                     Non-Null Count   Dtype  
---  ------                                                                     --------------   -----  
 0   What is your cumulative weighted average(CWA) / grade point average(GPA)?  120960 non-null  float64
 1   Were you able to increase your CWA/GPA last semester?                      120960 non-null  object 
 2   Do you have a personal time table?                                         120960 non-null  object 
 3   How many times do you study every week?                                    120960 non-null  int64  
 4   Do you always understand what you are taught at lectures?                  120960 non-null  object 
 5   How often have you been attending lectures?                                120960 non-null  object 
 6   Advice                                       

In [5]:
train_df.head(10)

What is your cumulative weighted average(CWA) / grade point average(GPA)?  ...                                             Advice
0                                              67.50                          ...  Increase study time and ask for help when faci...
1                                              71.75                          ...                Aim higher and don't be complacent 
2                                              60.00                          ...  Increase study time and ask for help when faci...
3                                              62.37                          ...  Increase study time and ask for help when faci...
4                                              56.00                          ...   Seek for a discipline and serious academic group
5                                              59.50                          ...  Increase study time and ask for help when faci...
6                                              67.00                          ...  Increase study time and ask for help when faci...
7                                              76.00                          ...  Increase study time and ask for help when faci...
8                                              64.50                          ...  Increase study time and ask for help when faci...
9                                              69.95                          ...  Increase study time and ask for help when faci...

[10 rows x 7 columns]

In [ ]:
col_list = list(train_df)
print(col_list)

['What is your cumulative weighted average(CWA) / grade point average(GPA)?', 'Were you able to increase your CWA/GPA last semester?', 'Do you have a personal time table?', 'How many times do you study every week?', 'Do you always understand what you are taught at lectures?', 'How often have you been attending lectures?', 'Advice']


In [ ]:
#list of columns
['What is your cumulative weighted average(CWA) / grade point average(GPA)?', 'Were you able to increase your CWA/GPA last semester?', 'Do you have a personal time table?', 'How many times do you study every week?', 'Do you always understand what you are taught at lectures?', 'How often have you been attending lectures?', 'Advice']

In [ ]:
#creating a dictionary for the labels
test_df = pd.read_csv(test_path)
my_advice = {}
k = 0
for i in test_df['Advice']:
  my_advice[k]= i
  k+=1
print(my_advice)

{0: 'Increase study time and ask for help when facing challenges', 1: "Aim higher and don't be complacent ", 2: 'Increase study time and ask for help when facing challenges', 3: 'Increase study time and ask for help when facing challenges', 4: 'Seek for a discipline and serious academic group', 5: 'Increase study time and ask for help when facing challenges', 6: 'Increase study time and ask for help when facing challenges', 7: 'Increase study time and ask for help when facing challenges', 8: 'Increase study time and ask for help when facing challenges', 9: 'Increase study time and ask for help when facing challenges', 10: 'Seek for a discipline and serious academic group', 11: "Aim higher and don't be complacent ", 12: 'Seek for a discipline and serious academic group', 13: "Aim higher and don't be complacent ", 14: 'Increase study time and ask for help when facing challenges', 15: 'Seek for a discipline and serious academic group', 16: "Aim higher and don't be complacent ", 17: 'Incre

In [ ]:
{0: 'Increase study time and ask for help when facing challenges', 1: "Aim higher and don't be complacent ", 2: 'Increase study time and ask for help when facing challenges', 3: 'Increase study time and ask for help when facing challenges', 4: 'Seek for a discipline and serious academic group', 5: 'Increase study time and ask for help when facing challenges', 6: 'Increase study time and ask for help when facing challenges', 7: 'Increase study time and ask for help when facing challenges', 8: 'Increase study time and ask for help when facing challenges', 9: 'Increase study time and ask for help when facing challenges', 10: 'Seek for a discipline and serious academic group', 11: "Aim higher and don't be complacent ", 12: 'Seek for a discipline and serious academic group', 13: "Aim higher and don't be complacent ", 14: 'Increase study time and ask for help when facing challenges', 15: 'Seek for a discipline and serious academic group', 16: "Aim higher and don't be complacent ", 17: 'Increase study time and ask for help when facing challenges', 18: 'Increase study time and ask for help when facing challenges', 19: 'Increase study time and ask for help when facing challenges', 20: 'Increase study time and ask for help when facing challenges', 21: 'Seek for a discipline and serious academic group', 22: 'Increase study time and ask for help when facing challenges', 23: "Aim higher and don't be complacent ", 24: 'Increase study time and ask for help when facing challenges', 25: 'Increase study time and ask for help when facing challenges', 26: 'Increase study time and ask for help when facing challenges', 27: 'Increase study time and ask for help when facing challenges', 28: "Aim higher and don't be complacent ", 29: 'Increase study time and ask for help when facing challenges', 30: 'Increase study time and ask for help when facing challenges', 31: 'Increase study time and ask for help when facing challenges', 32: 'Seek for a discipline and serious academic group', 33: 'Increase study time and ask for help when facing challenges', 34: 'Increase study time and ask for help when facing challenges', 35: "Aim higher and don't be complacent ", 36: 'Increase study time and ask for help when facing challenges', 37: 'Increase study time and ask for help when facing challenges', 38: "Aim higher and don't be complacent ", 39: "Aim higher and don't be complacent ", 40: 'Increase study time and ask for help when facing challenges', 41: 'Increase study time and ask for help when facing challenges', 42: 'Increase study time and ask for help when facing challenges', 43: "Aim higher and don't be complacent ", 44: "Aim higher and don't be complacent ", 45: 'Increase study time and ask for help when facing challenges', 46: 'Seek for a discipline and serious academic group', 47: 'Seek for a discipline and serious academic group', 48: "Aim higher and don't be complacent ", 49: 'Increase study time and ask for help when facing challenges', 50: 'Increase study time and ask for help when facing challenges', 51: 'Seek for a discipline and serious academic group', 52: 'Seek for a discipline and serious academic group', 53: 'Seek for a discipline and serious academic group', 54: 'Increase study time and ask for help when facing challenges', 55: 'Seek for a discipline and serious academic group', 56: 'Seek for a discipline and serious academic group', 57: 'Seek for a discipline and serious academic group', 58: 'Increase study time and ask for help when facing challenges', 59: 'Seek for a discipline and serious academic group', 60: 'Increase study time and ask for help when facing challenges', 61: 'Increase study time and ask for help when facing challenges', 62: 'Seek for a discipline and serious academic group', 63: 'Increase study time and ask for help when facing challenges', 64: 'Seek for a discipline and serious academic group', 65: "Aim higher and don't be complacent ", 66: "Aim higher and don't be complacent ", 67: 'Seek for a discipline and serious academic group', 68: "Aim higher and don't be complacent ", 69: 'Seek for a discipline and serious academic group', 70: 'Increase study time and ask for help when facing challenges', 71: 'Increase study time and ask for help when facing challenges', 72: 'Increase study time and ask for help when facing challenges', 73: 'Seek for a discipline and serious academic group', 74: 'Increase study time and ask for help when facing challenges', 75: 'Increase study time and ask for help when facing challenges', 76: 'Increase study time and ask for help when facing challenges', 77: "Aim higher and don't be complacent ", 78: 'Increase study time and ask for help when facing challenges', 79: 'Seek for a discipline and serious academic group', 80: 'Seek for a discipline and serious academic group', 81: "Aim higher and don't be complacent ", 82: "Aim higher and don't be complacent ", 83: 'Increase study time and ask for help when facing challenges', 84: 'Increase study time and ask for help when facing challenges', 85: 'Increase study time and ask for help when facing challenges', 86: 'Seek for a discipline and serious academic group', 87: 'Seek for a discipline and serious academic group', 88: 'Increase study time and ask for help when facing challenges', 89: "Aim higher and don't be complacent ", 90: "Aim higher and don't be complacent ", 91: 'Increase study time and ask for help when facing challenges', 92: 'Increase study time and ask for help when facing challenges', 93: 'Seek for a discipline and serious academic group', 94: 'Increase study time and ask for help when facing challenges', 95: "Aim higher and don't be complacent ", 96: 'Increase study time and ask for help when facing challenges', 97: 'Increase study time and ask for help when facing challenges', 98: 'Seek for a discipline and serious academic group', 99: 'Seek for a discipline and serious academic group', 100: "Aim higher and don't be complacent ", 101: 'Increase study time and ask for help when facing challenges', 102: 'Increase study time and ask for help when facing challenges', 103: 'Increase study time and ask for help when facing challenges', 104: "Aim higher and don't be complacent ", 105: 'Seek for a discipline and serious academic group', 106: 'Increase study time and ask for help when facing challenges', 107: 'Seek for a discipline and serious academic group', 108: 'Increase study time and ask for help when facing challenges', 109: 'Increase study time and ask for help when facing challenges', 110: 'Increase study time and ask for help when facing challenges', 111: "Aim higher and don't be complacent ", 112: 'Increase study time and ask for help when facing challenges', 113: 'Increase study time and ask for help when facing challenges', 114: "Aim higher and don't be complacent ", 115: "Aim higher and don't be complacent ", 116: 'Increase study time and ask for help when facing challenges', 117: "Aim higher and don't be complacent ", 118: 'Increase study time and ask for help when facing challenges', 119: 'Increase study time and ask for help when facing challenges', 120: 'Increase study time and ask for help when facing challenges', 121: "Aim higher and don't be complacent ", 122: "Aim higher and don't be complacent ", 123: "Aim higher and don't be complacent ", 124: 'Increase study time and ask for help when facing challenges', 125: 'Seek for a discipline and serious academic group', 126: 'Increase study time and ask for help when facing challenges', 127: 'Seek for a discipline and serious academic group', 128: 'Seek for a discipline and serious academic group', 129: 'Increase study time and ask for help when facing challenges', 130: 'Increase study time and ask for help when facing challenges', 131: 'Increase study time and ask for help when facing challenges', 132: 'Increase study time and ask for help when facing challenges', 133: 'Increase study time and ask for help when facing challenges', 134: 'Increase study time and ask for help when facing challenges'}

In [6]:
#replacing some categorical columns with numberic columns
train_df = pd.get_dummies(data = train_df, columns =['Were you able to increase your CWA/GPA last semester?','Do you have a personal time table?','Do you always understand what you are taught at lectures?','How often have you been attending lectures?'] )

In [7]:
train_df.head(10)

What is your cumulative weighted average(CWA) / grade point average(GPA)?  ...  How often have you been attending lectures?_seldom
0                                              67.50                          ...                                                  1 
1                                              71.75                          ...                                                  0 
2                                              60.00                          ...                                                  1 
3                                              62.37                          ...                                                  0 
4                                              56.00                          ...                                                  1 
5                                              59.50                          ...                                                  1 
6                                              67.00                          ...                                                  0 
7                                              76.00                          ...                                                  0 
8                                              64.50                          ...                                                  0 
9                                              69.95                          ...                                                  1 

[10 rows x 12 columns]

In [ ]:
#change some numeric columns to integers or float types
#train_df.astype({'Dependents': 'int64','Loan_Amount_Term': 'int64','ApplicantIncome': 'float64'}).dtypes

In [8]:
#creating data for ML
X = train_df.drop(['Advice'], axis = 1)

y = train_df['Advice']


In [9]:
#splitting data into training and validation samples
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [10]:
#Training random forest classifier
rft = RandomForestClassifier(n_estimators=10)
rft.fit(X_train,y_train)

# Trained Model Evaluation on Validation Dataset
confidence = rft.score(X_test, y_test)
# Validation Data Prediction
preds = rft.predict(X_test)
# Model Validation Accuracy
accuracy = accuracy_score(y_test, preds)
# Model Confusion Matrix
conf_mat = confusion_matrix(y_test, preds)
# Model Classification Report
clf_report = classification_report(y_test, preds)

print(confidence)
print('\n')
print(accuracy)
print('\n')
print(conf_mat)
print('\n')
print(clf_report)

0.968777557319224


0.968777557319224


[[ 7941     0     0]
 [    0 19118   578]
 [    0   555  8096]]


                                                             precision    recall  f1-score   support

                        Aim higher and don't be complacent        1.00      1.00      1.00      7941
Increase study time and ask for help when facing challenges       0.97      0.97      0.97     19696
           Seek for a discipline and serious academic group       0.93      0.94      0.93      8651

                                                   accuracy                           0.97     36288
                                                  macro avg       0.97      0.97      0.97     36288
                                               weighted avg       0.97      0.97      0.97     36288



In [ ]:
['What is your cumulative weighted average(CWA) / grade point average(GPA)?','How many times do you study every week?', 'Were you able to increase your CWA/GPA last semester?', 'Do you have a personal time table?', 'Do you always understand what you are taught at lectures?', 'How often have you been attending lectures?']

In [ ]:
#new_im = [67.50, 2, 0, 1, 1, 0, 1, 0, 0, 0, 1]

In [13]:
param = ['What is your cumulative weighted average(CWA) / grade point average(GPA)?','How many times do you study every week?', 'Were you able to increase your CWA/GPA last semester?', 'Do you have a personal time table?', 'Do you always understand what you are taught at lectures?', 'How often have you been attending lectures?']

In [ ]:
#Assume inputs
#input_vals = ['67.50','Yes','No','2','No','seldom']

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120960 entries, 0 to 120959
Data columns (total 11 columns):
 #   Column                                                                     Non-Null Count   Dtype  
---  ------                                                                     --------------   -----  
 0   What is your cumulative weighted average(CWA) / grade point average(GPA)?  120960 non-null  float64
 1   How many times do you study every week?                                    120960 non-null  int64  
 2   Were you able to increase your CWA/GPA last semester?_No                   120960 non-null  uint8  
 3   Were you able to increase your CWA/GPA last semester?_Yes                  120960 non-null  uint8  
 4   Do you have a personal time table?_No                                      120960 non-null  uint8  
 5   Do you have a personal time table?_Yes                                     120960 non-null  uint8  
 6   Do you always understand what you are taught

In [22]:
#preprocessing model to make single predictions
myInput = []
for i in range(0,11):
    myInput.append(0)
print(myInput)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [23]:
 input_vals = []

for i in range(0,len(param)):
  print(param[i])
  vals =input('Enter: ')
  #store input in a list
  input_vals.append(vals)

print(input_vals)

What is your cumulative weighted average(CWA) / grade point average(GPA)?
Enter: 50.5
How many times do you study every week?
Enter: 3
Were you able to increase your CWA/GPA last semester?
Enter: Yes
Do you have a personal time table?
Enter: Yes
Do you always understand what you are taught at lectures?
Enter: Yes
How often have you been attending lectures?
Enter: seldom
['50.5', '3', 'Yes', 'Yes', 'Yes', 'seldom']


In [24]:
my_im_dict = {}
k = 0
for i in input_vals:
  my_im_dict[k]= i
  k+=1

In [25]:
print(my_im_dict)

{0: '50.5', 1: '3', 2: 'Yes', 3: 'Yes', 4: 'Yes', 5: 'seldom'}


In [26]:
# preprocessing user input for the machine model
for i in range(0,len(myInput)):
    if i < 2:
      myInput[i] = my_im_dict[i]

    elif i == 2:
      if my_im_dict[i] == "No": myInput[i] = 1
      else: myInput[i+1] = 1
      

    elif i == 3:
      if my_im_dict[i] == "No": myInput[i+1] = 1
      else: myInput[i+2] = 1
      
      

    elif i == 4:
      if my_im_dict[i] == "No": myInput[i+2] = 1
      else: myInput[i+3] = 1
      
      

    elif i == 5:
      if my_im_dict[i] == "seldom": myInput[i+3] = 1
      elif my_im_dict[i] == "often" : myInput[i+4] = 1
      else: myInput[i+5] = 1
      

In [27]:
print(myInput)

['50.5', '3', 0, 1, 0, 1, 0, 1, 1, 0, 0]


In [28]:
input_mat = [myInput]
pred1 = rft.predict(input_mat)
print(pred1)

['Seek for a discipline and serious academic group']


In [29]:
#Training decision tree classifier
dt = DecisionTreeClassifier(criterion='entropy')
dt.fit(X_train,y_train)

# Trained Model Evaluation on Validation Dataset
confidence = dt.score(X_test, y_test)
# Validation Data Prediction
preds = dt.predict(X_test)
# Model Validation Accuracy
accuracy = accuracy_score(y_test, preds)
# Model Confusion Matrix
conf_mat = confusion_matrix(y_test, preds)
# Model Classification Report
clf_report = classification_report(y_test, preds)

print(confidence)
print('\n')
print(accuracy)
print('\n')
print(conf_mat)
print('\n')
print(clf_report)

0.9684744268077602


0.9684744268077602


[[ 7941     0     0]
 [    0 18829   867]
 [    0   277  8374]]


                                                             precision    recall  f1-score   support

                        Aim higher and don't be complacent        1.00      1.00      1.00      7941
Increase study time and ask for help when facing challenges       0.99      0.96      0.97     19696
           Seek for a discipline and serious academic group       0.91      0.97      0.94      8651

                                                   accuracy                           0.97     36288
                                                  macro avg       0.96      0.97      0.97     36288
                                               weighted avg       0.97      0.97      0.97     36288



In [30]:
input_mat = [myInput]
pred2 = dt.predict(input_mat)
print(pred2)

['Seek for a discipline and serious academic group']


In [31]:
#Training KNN classifier
#KNN Approach
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn.fit(X_train,y_train)

# Trained Model Evaluation on Validation Dataset
confidence = knn.score(X_test, y_test)
# Validation Data Prediction
preds = knn.predict(X_test)
# Model Validation Accuracy
accuracy = accuracy_score(y_test, preds)
# Model Confusion Matrix
conf_mat = confusion_matrix(y_test, preds)
# Model Classification Report
clf_report = classification_report(y_test, preds)

print(confidence)
print('\n')
print(accuracy)
print('\n')
print(conf_mat)
print('\n')
print(clf_report)

0.968722442680776


0.968722442680776


[[ 7941     0     0]
 [    0 19111   585]
 [    0   550  8101]]


                                                             precision    recall  f1-score   support

                        Aim higher and don't be complacent        1.00      1.00      1.00      7941
Increase study time and ask for help when facing challenges       0.97      0.97      0.97     19696
           Seek for a discipline and serious academic group       0.93      0.94      0.93      8651

                                                   accuracy                           0.97     36288
                                                  macro avg       0.97      0.97      0.97     36288
                                               weighted avg       0.97      0.97      0.97     36288



In [32]:
input_mat = [myInput]
pred4 = knn.predict(input_mat)
print(pred4)

['Seek for a discipline and serious academic group']


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:171: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  X = check_array(X, accept_sparse='csr')
/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_base.py:605: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  X = check_array(X, accept_sparse='csr')
